apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config-pv
  namespace: default
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /volume1/container-configs/jellyfin-config
    server: <REPLACE>
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: jellyfin-config-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
