apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
  namespace: default
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  nfs:
    path: /volume1/media
    server:
      valueFrom:
        secretKeyRef:
          name: nas-secret
          key: NAS_IP
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: media-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
