apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-container-configs
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-container-configs
