apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-media
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  storageClassName: nfs-media
