apiVersion: v1
kind: PersistentVolume
metadata:
  name: crafty-pv
  namespace: default
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /volume1/container-configs/minecraft
    server: '192.168.2.10'
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: crafty-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crafty-data
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
