apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crafty-data
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: nfs-client
