apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent-vpn
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      securityContext:
        sysctls:
          - name: net.ipv4.conf.all.src_valid_mark
            value: '1'
      containers:
        - name: gluetun
          image: qmcgaw/gluetun
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: VPN_SERVICE_PROVIDER
              value: 'mullvad'
            - name: VPN_TYPE
              value: 'wireguard'
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: mullvad-vpn-secrets
                  key: WIREGUARD_PRIVATE_KEY
            - name: WIREGUARD_ADDRESSES
              valueFrom:
                secretKeyRef:
                  name: mullvad-vpn-secrets
                  key: WIREGUARD_ADDRESSES
            - name: TZ
              value: 'America/New_York'
            - name: UPDATER_PERIOD
              value: '24h'
          volumeMounts:
            - name: gluetun-config
              mountPath: /gluetun
          ports:
            - containerPort: 6881
              protocol: TCP
            - containerPort: 6881
              protocol: UDP
            - containerPort: 8080
              protocol: TCP

        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest
          securityContext:
            runAsUser: 13007
            runAsGroup: 13000
          env:
            - name: PUID
              value: '13007'
            - name: PGID
              value: '13000'
            - name: UMASK
              value: '002'
            - name: TZ
              value: 'America/New_York'
            - name: WEBUI_PORT
              value: '8080'
          volumeMounts:
            - name: qbittorrent-config
              mountPath: /config
            - name: qbittorrent-torrents
              mountPath: /data/torrents

      volumes:
        - name: gluetun-config
          persistentVolumeClaim:
            claimName: gluetun-config-pvc
        - name: qbittorrent-config
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc
        - name: qbittorrent-torrents
          persistentVolumeClaim:
            claimName: qbittorrent-torrents-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-service
  namespace: default
spec:
  selector:
    app: qbittorrent
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
