apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      volumes:
        - name: qbittorrent-config
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc
        - name: qbittorrent-torrents
          persistentVolumeClaim:
            claimName: qbittorrent-torrents-pvc
        - name: vpn-config
          secret:
            secretName: vpn-config
            items:
              - key: client.ovpn
                path: client.ovpn
        - name: vpn-auth
          secret:
            secretName: vpn-auth
            items:
              - key: auth.txt
                path: auth.txt

      initContainers:
        - name: vpn
          image: dperson/openvpn-client
          restartPolicy: Always
          command: ['/bin/sh', '-c']
          args:
            [
              "openvpn --config 'vpn/client.ovpn' --auth-user-pass 'vpn/auth.txt' --script-security 3;",
            ]
          stdin: true
          tty: true
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: TZ
              value: 'America/New_York'
          volumeMounts:
            - name: vpn-config
              mountPath: /vpn/client.ovpn
              subPath: client.ovpn
            - name: vpn-auth
              mountPath: /vpn/auth.txt
              subPath: auth.txt

      containers:
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest
          env:
            - name: PUID
              value: '13007'
            - name: PGID
              value: '13000'
            - name: TZ
              value: 'America/New_York'
            - name: WEBUI_PORT
              value: '8081'
          volumeMounts:
            - name: qbittorrent-config
              mountPath: /config
            - name: qbittorrent-torrents
              mountPath: /data/torrents
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  geo_info=$(curl -s --max-time 5 http://ipinfo.io/json)
                  state=$(echo $geo_info | grep -oP '"region":\s*"\K[^"]+')
                  if [ "$state" == "Florida" ]; then
                    exit 1 
                  fi
                  exit 0
            initialDelaySeconds: 10
            periodSeconds: 300
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1

---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-service
  namespace: default
spec:
  selector:
    app: qbittorrent
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
