apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: qbittorrent-isolated
  namespace: media
spec:
  podSelector:
    matchLabels:
      app: qbittorrent
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: gluetun
