apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-torrents-pv
  namespace: default
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /volume1/media/torrents
    server: '192.168.2.10'
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: qbittorrent-torrents-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-torrents-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
