apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
        - name: n8n
          image: n8nio/n8n:latest
          env:
            - name: N8N_BASIC_AUTH_ACTIVE
              value: "true"
            - name: N8N_BASIC_AUTH_USER
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: username
            - name: N8N_BASIC_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: password
            - name: N8N_HOST
              value: "n8n.hexagonlabs.cloud"
            - name: N8N_PORT
              value: "5678"
            - name: N8N_PROTOCOL
              value: "https"
            - name: N8N_PATH
              value: "/"
            - name: GENERIC_TIMEZONE
              value: "America/New_York"
            - name: N8N_LOG_LEVEL
              value: "info"
            - name: PATH
              value: "/opt/local-bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
          ports:
            - containerPort: 5678
          volumeMounts:
            - name: n8n-data
              mountPath: /home/node/.n8n
            - name: shared-bin
              mountPath: /opt/local-bin
        - name: wol-server
          image: python:3.11-alpine
          command: ["sh", "-c"]
          args:
            - |
              pip install wakeonlan && \
              echo "$WOL_SERVER" > /wol.py && \
              python3 /wol.py
          env:
            - name: WOL_SERVER
              value: |
                from http.server import BaseHTTPRequestHandler, HTTPServer
                import subprocess

                class Handler(BaseHTTPRequestHandler):
                    def do_POST(self):
                        if self.path == '/wake':
                            subprocess.run(["wakeonlan", "00:11:22:33:44:55"])
                            self.send_response(200)
                            self.end_headers()
                            self.wfile.write(b"Magic packet sent")
                        else:
                            self.send_response(404)
                            self.end_headers()

                HTTPServer(("", 9001), Handler).serve_forever()
          ports:
            - containerPort: 9001
      volumes:
        - name: n8n-data
          persistentVolumeClaim:
            claimName: n8n-pvc
        - name: shared-bin
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: n8n
  namespace: default
spec:
  selector:
    app: n8n
  ports:
    - port: 80
      targetPort: 5678
  type: ClusterIP
