apiVersion: v1
kind: PersistentVolume
metadata:
  name: n8n-pv
  namespace: default
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /volume1/container-configs/n8n-config
    server: '192.168.2.10'
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: n8n-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
