apiVersion: v1
kind: ConfigMap
metadata:
  name: wol-script
data:
  wol.py: |
    from http.server import BaseHTTPRequestHandler, HTTPServer
    import subprocess
    from urllib.parse import urlparse, parse_qs

    class Handler(BaseHTTPRequestHandler):
        def do_POST(self):
            if self.path.startswith("/wake"):
                qs = parse_qs(urlparse(self.path).query)
                mac = qs.get("mac", [None])[0]
                if not mac:
                    self.send_response(400)
                    self.end_headers()
                    self.wfile.write(b"Missing mac")
                    return
                subprocess.run(["wakeonlan", mac])
                self.send_response(200)
                self.end_headers()
                self.wfile.write(f"Sent to {mac}".encode())
            else:
                self.send_response(404)
                self.end_headers()

    HTTPServer(("", 9001), Handler).serve_forever()
