apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  destination:
    namespace: immich
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 16.6.4
    helm:
      values: |
        auth:
          username: immich
          existingSecret: immich-secret
          secretKeys:
            userPasswordKey: DB_PASSWORD
          database: immich
        primary:
          persistence:
            enabled: true
            size: 10Gi
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
