apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://immich-app.github.io/immich-charts
    chart: immich
    targetRevision: 0.9.2
    helm:
      values: |
        postgres:
          enabled: false

        redis:
          enabled: false

        envFrom:
          - secretRef:
              name: immich-secret

        env:
          DB_USERNAME: immich
          DB_DATABASE_NAME: immich
          DB_HOSTNAME: immich-postgres-postgresql
          REDIS_HOSTNAME: immich-redis-master

        persistence:
          library:
            enabled: true
            existingClaim: immich-media-pvc

  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
