postgres:
  enabled: false

redis:
  enabled: false

envFrom:
  - secretRef:
      name: immich-secret

env:
  DB_USERNAME: immich
  DB_DATABASE_NAME: immich
  DB_HOSTNAME: immich-postgres-postgresql
  REDIS_HOSTNAME: immich-redis-master

persistence:
  library:
    enabled: true
    existingClaim: immich-media-pvc
