apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: immich
    repo: https://immich.app/helm-charts
    version: 0.5.2
    releaseName: immich
    namespace: immich
    valuesFile: helm-values.yaml
