apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-media-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.2.10
    path: /volume1/immich
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-media-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: nfs-client
  volumeName: immich-media-pv
