apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:develop
          ports:
            - containerPort: 9696
          volumeMounts:
            - name: config
              mountPath: /config
          env:
            - name: PUID
              value: '13006'
            - name: PGID
              value: '13000'
            - name: TZ
              value: 'America/New_York'
            - name: UMASK
              value: '002'
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: prowlarr-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: default
spec:
  selector:
    app: prowlarr
  ports:
    - port: 9696
      targetPort: 9696
  type: ClusterIP
