apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: immich
spec:
  destination:
    namespace: immich
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 19.5.4
    helm:
      values: |
        architecture: standalone
        auth:
          enabled: false
        master:
          persistence:
            enabled: true
            size: 2Gi
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---

