apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '2'
spec:
  project: default
  source:
    repoURL: 'https://github.com/nel-thedev/k3s-arda.git'
    targetRevision: main
    path: apps/kube-prometheus-stack
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
