apiVersion: v1
kind: Service
metadata:
  name: velocity-public
  namespace: minecraft
spec:
  type: NodePort
  selector:
    app: velocity
  ports:
    - name: minecraft
      port: 25565
      targetPort: 25565
      nodePort: 30065
      protocol: TCP
