apiVersion: v1
kind: Service
metadata:
  name: ark-server
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.2.241
  selector:
    app: ark-server
  ports:
    - name: game
      port: 7777
      protocol: UDP
      targetPort: 7777
    - name: raw
      port: 7778
      protocol: UDP
      targetPort: 7778
    - name: query
      port: 27015
      protocol: UDP
      targetPort: 27015
