apiVersion: v1
kind: PersistentVolume
metadata:
  name: ark-pv
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  nfs:
    path: /volume1/container-configs/ark-data
    server: '192.168.2.10'
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ark-pvc
  namespace: ark-server
spec:
  storageClassName: ''
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  volumeName: ark-pv
---

