apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-config-template
  namespace: cctv
data:
  config.yml.tpl: |
    mqtt: null

    detectors:
      cpu1:
        type: cpu

    cameras:
      birdfeeder:
        ffmpeg:
          inputs:
            - path: ${RTSP_URL}
              roles: [detect]
        detect:
          enabled: true
          width: 1280
          height: 720
        record:
          enabled: false
        snapshots:
          enabled: true
          timestamp: false
          retain:
            default: 1
        clips:
          enabled: true
          pre_capture: 5
          post_capture: 5
          retain:
            default: 0

    # Send event webhooks when clips finish (“end”)
    # Frigate sends JSON with paths well use to upload to Discord
    webhooks:
      - url: ${UPLOADER_URL}/frigate
        verify_ssl: false
