apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate
  namespace: cctv
  labels:
    app: frigate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frigate
  template:
    metadata:
      labels:
        app: frigate
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
        - name: copy-config
          image: busybox
          command: ["/bin/sh", "-c", "cp /input/* /output/ && ls -l /output"]
          volumeMounts:
            - name: frigate-config
              mountPath: /input
            - name: frigate-config-writable
              mountPath: /output
              
      containers:
        - name: frigate
          image: ghcr.io/blakeblackshear/frigate:stable
          imagePullPolicy: IfNotPresent
          env:
            - name: FRIGATE_CONFIG_FILE
              value: /config/config.yml
            # - name: RTSP_URL
            #   valueFrom:
            #     secretKeyRef:
            #       name: frigate-secrets
            #       key: RTSP_URL
          envFrom:
            - secretRef:
                name: frigate-secrets
          ports:
            - name: http
              containerPort: 5000
          volumeMounts:
            - name: frigate-config-writable
              mountPath: /config
            - name: frigate-storage
              mountPath: /media/frigate
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "2000m"
              memory: "2Gi"
      volumes:
        - name: frigate-config
          configMap:
            name: frigate-config
            items:
              - key: config.yml
                path: config.yml
        - name: frigate-config-writable
          emptyDir: {}
        - name: frigate-storage
          persistentVolumeClaim:
            claimName: frigate-pvc
