apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-pv
  namespace: cctv
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  nfs:
    path: /volume1/media
    server: '192.168.2.10'
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: cctv
    name: frigate-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-pvc
  namespace: cctv
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
