apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-config-pv
  namespace: default
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /volume1/container-configs/audiobookshelf-config
    server: '192.168.2.10'
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: audiobookshelf-config-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-config-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
