apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:latest
          ports:
            - containerPort: 13378
          volumeMounts:
            - name: config
              mountPath: /config
            - name: audiobooks
              mountPath: /audiobooks
            - name: podcasts
              mountPath: /podcasts
            - name: metadata
              mountPath: /metadata
          env:
            - name: PUID
              value: '13002'
            - name: PGID
              value: '13000'
            - name: TZ
              value: 'America/New_York'
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: audiobookshelf-config-pvc
        - name: audiobooks
          persistentVolumeClaim:
            claimName: audiobookshelf-audiobooks-pvc
        - name: podcasts
          persistentVolumeClaim:
            claimName: audiobookshelf-podcasts-pvc
        - name: metadata
          persistentVolumeClaim:
            claimName: audiobookshelf-metadata-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: audiobookshelf
  namespace: default
spec:
  selector:
    app: audiobookshelf
  ports:
    - port: 7878
      targetPort: 7878
  type: ClusterIP
