apiVersion: v1
kind: ConfigMap
metadata:
  name: external-secrets-placeholder
  namespace: external-secrets

---

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: external-secrets
resources:
  - https://raw.githubusercontent.com/external-secrets/external-secrets/v0.10.3/deploy/install-bundle.yaml
namespace: external-secrets
