apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  namespace: nfs-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-volume
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: 'nfs-provisioner'
            - name: NFS_SERVER
              valueFrom:
                secretKeyRef:
                  name: nas-secret
                  key: NAS_IP
            - name: NFS_PATH
              value: '/volume1/media'
      volumes:
        - name: nfs-volume
          nfs:
            server:
              valueFrom:
                secretKeyRef:
                  name: nas-secret
                  key: NAS_IP
            path: /volume1/media
