resources:
  - deployment.yaml
  - nfs-provisioner-rbac.yaml
  - nfs-provisioner-rolebinding.yaml
  - nfs-service-account.yaml
  - storageclass.yaml
  - namespace.yaml

secrets:
  -name: nas-secret
   namespace: default