apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: nas-config
    literals:
      - NAS_IP=<REPLACE>

resources:
  - deployment.yaml
  - nfs-provisioner-rbac.yaml
  - nfs-provisioner-rolebinding.yaml
  - nfs-service-account.yaml
  - storageclass.yaml
  - namespace.yaml
# secrets:
#   -name: nas-secret
#   #  namespace: default

vars:
  - name: NAS_IP
    objref:
      kind: ConfigMap
      name: nas-config
      namespace: default
      apiVersion: v1
    fieldref:
      fieldpath: data.NAS_IP
