apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nfs-provisioner

# configMapGenerator:
#   - name: nas-config
#   - namespace: nfs-provisioner
#     literals:
#       - NAS_IP=<REPLACE>

resources:
  - deployment.yaml
  - nfs-provisioner-rbac.yaml
  - nfs-provisioner-rolebinding.yaml
  - nfs-service-account.yaml
  - storageclass.yaml
  - namespace.yaml
# vars:
#   - name: NAS_IP
#     objref:
#       kind: ConfigMap
#       name: nas-config
#       namespace: nfs-provisioner
#       apiVersion: v1
#     fieldref:
#       fieldpath: data.NAS_IP
