apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nfs-provisioner

resources:
  - deployment.yaml
  - nfs-provisioner-rbac.yaml
  - nfs-provisioner-rolebinding.yaml
  - nfs-service-account.yaml
  - storageclass.yaml
  - namespace.yaml
