apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitch-ai-bot
  namespace: bots
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitch-ai-bot
  template:
    metadata:
      labels:
        app: twitch-ai-bot
    spec:
      containers:
        - name: bot
          image: ghcr.io/nel-thedev/twitch-ai-bot:latest
          env:
            - name: TWITCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: twitch-ai-bot-secret
                  key: TWITCH_USERNAME

            - name: TWITCH_OAUTH
              valueFrom:
                secretKeyRef:
                  name: twitch-ai-bot-secret
                  key: TWITCH_OAUTH

            - name: CHANNEL
              valueFrom:
                secretKeyRef:
                  name: twitch-ai-bot-secret
                  key: CHANNEL

            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: twitch-ai-bot-secret
                  key: OPENAI_API_KEY

            - name: ADMINS
              value: sonofneltv


